-- ============================================================
-- 装備手帳: 公開の既定値を「公開」に変更する migration 起案
-- migration名: equipment_notebook_public_default_2026_08_04
-- 状態: ★適用済み★（2026-08-12 ローカルPCから適用・migration名は上記のとおり登録済み）
--       適用前 column_default = false → 適用後 true を確認。
--       既存行への影響なし（適用の前後とも is_public=true が14件・false は0件）。
--       ※ 2026-08-04 起案時に最重要の注意点だった「パイロット6件を false のまま守る」は、
--         適用時点で既に本人たちが公開に切り替えており false の行が0件だったため、
--         守るべき既存行そのものが存在しなかった。
--       ※ 列のdefaultは匿名RESTから見えないため、確認はローカルPCからしか行えない。
--       select column_default from information_schema.columns
--        where table_name='equipment_records' and column_name='is_public';
--
-- 【以下は起案当時（2026-08-04〜08-06）の記録。経緯として残す】
-- ⚠️ 未適用だが実害はない（2026-08-06 全経路を調査して確認）。
--   equipment_records への insert は equipment-edit.html の1箇所だけで、そこは
--   is_public を必ず明示送信している（下の「補足」のとおり）。よって列のdefaultは使われない。
--   新規の手帳が既定で公開になるかどうかは、いまもフロントのトグル初期状態が決めている。
--   このmigrationは**DB側にも意図を残すための整合目的**なので、急いで流す必要はない。
--   ただし将来スクリプトやバッチから直接 insert する経路を足すときは、
--   このmigrationを先に適用するか、そちらでも is_public を明示すること。
--
-- 方針変更（2026-08-04 ユーザー判断）:
--   フェーズB当初は「公開はオプトイン（既定 false）」で実装したが、
--   「公開前提」に変更する。ただし本番リリース前に、
--   既存パイロット6件については個別に公開の了解を取る。
--
-- ⚠️ 重要: 既存行は変更しない。
--   alter column ... set default はこれから作られる行にのみ効き、
--   既に false で保存されている6件は非公開のまま保たれる。
--   パイロット参加者は「パイロット期間中は非公開」という前提で記入しているため、
--   本人の同意なく公開に切り替えてはいけない（HANDOFF.md L136 の方針）。
--
-- 補足: フロント（equipment-edit.html）は insert 時に is_public を必ず明示送信するため、
--   このカラム既定値は実質的に使われない。意図を DB 側にも残すための整合目的の変更。
--   実際の既定を決めているのはフロントのトグル初期状態（record ? record.is_public : true）。
-- ============================================================

alter table public.equipment_records
  alter column is_public set default true;

-- ============================================================
-- 適用後の確認（2026-08-12 に実施済み。結果は冒頭の「状態」を見ること）
-- ※ 以下の期待値は起案当時の想定。実際の適用時は false の行が0件だった。
--   select is_public, count(*) from public.equipment_records group by is_public;
--     → 方針変更の直後は false が6件・true が0件（または本人が公開した分のみ）
--   select column_default from information_schema.columns
--    where table_schema='public' and table_name='equipment_records' and column_name='is_public';
--     → true
--
-- ロールバック:
--   alter table public.equipment_records alter column is_public set default false;
-- ============================================================
