-- 2026-09-30 棚卸し Phase 4：スキーマの写し（database_schema.sql）を再生成するための関数。
-- `supabase db dump` の代替（このプロジェクトでは Supabase CLI をローカルに置いていない）。
-- 呼び出し元＝ py/dump_schema.py（service_role）。anon / authenticated / PUBLIC からは実行不可。
-- 返すのは public スキーマの DDL 相当のテキスト（enum・テーブル・制約・RLS・インデックス・ビュー・関数・トリガー・ポリシー）。
-- 実行しても DB は変わらない（pg_catalog を読むだけ）。

create or replace function public.schema_snapshot()
returns text
language sql
stable
set search_path = pg_catalog, public
as $$
with
enums as (
  select string_agg(format('create type public.%I as enum (%s);', t.typname,
           (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) from pg_enum e where e.enumtypid = t.oid)),
         E'\n' order by t.typname) as txt
  from pg_type t join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' and t.typtype = 'e'
),
tables as (
  select string_agg(ddl, E'\n\n' order by tbl) as txt from (
    select c.relname as tbl,
      format(E'create table public.%I (\n%s\n);', c.relname,
        (select string_agg(format('  %I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
                  case when a.attidentity = 'a' then ' generated always as identity'
                       when a.attidentity = 'd' then ' generated by default as identity' else '' end,
                  case when a.attnotnull then ' not null' else '' end,
                  case when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end),
                E',\n' order by a.attnum)
           from pg_attribute a
           left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
          where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped))
      || coalesce((select E'\n' || string_agg(format('alter table public.%I add constraint %I %s;', c.relname, con.conname, pg_get_constraintdef(con.oid)), E'\n'
                    order by case con.contype when 'p' then 1 when 'u' then 2 when 'c' then 3 else 4 end, con.conname)
                   from pg_constraint con where con.conrelid = c.oid), '')
      || case when c.relrowsecurity then format(E'\nalter table public.%I enable row level security;', c.relname) else '' end
      || case when obj_description(c.oid, 'pg_class') is not null
              then format(E'\ncomment on table public.%I is %L;', c.relname, obj_description(c.oid, 'pg_class')) else '' end
      as ddl
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r') s
),
indexes as (
  select string_agg(indexdef || ';', E'\n' order by tablename, indexname) as txt
  from pg_indexes
  where schemaname = 'public' and indexname not in (select conname from pg_constraint)
),
views as (
  select string_agg(format(E'create or replace view public.%I%s as\n%s', v.viewname,
           coalesce(' with (' || array_to_string(c.reloptions, ', ') || ')', ''), pg_get_viewdef(c.oid, true)), E'\n\n' order by v.viewname) as txt
  from pg_views v
  join pg_namespace n on n.nspname = v.schemaname
  join pg_class c on c.relname = v.viewname and c.relnamespace = n.oid
  where v.schemaname = 'public'
),
funcs as (
  select string_agg(pg_get_functiondef(p.oid) || ';' || coalesce(E'\n-- acl: ' || array_to_string(p.proacl, ' '), E'\n-- acl: (default)'),
                    E'\n\n' order by p.proname, p.oid) as txt
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f', 'p') and p.proname <> 'schema_snapshot'
),
trigs as (
  select string_agg(pg_get_triggerdef(t.oid) || ';', E'\n' order by c.relname, t.tgname) as txt
  from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
),
pols as (
  select string_agg(format('create policy %I on public.%I as %s for %s to %s%s%s;', policyname, tablename, lower(permissive), cmd, array_to_string(roles, ', '),
           case when qual is not null then E'\n  using (' || qual || ')' else '' end,
           case when with_check is not null then E'\n  with check (' || with_check || ')' else '' end),
         E'\n' order by tablename, policyname) as txt
  from pg_policies where schemaname = 'public'
),
exts as (
  select string_agg(format('-- %s %s', extname, extversion), E'\n' order by extname) as txt from pg_extension
)
select
     E'-- ===== extensions =====\n' || coalesce((select txt from exts), '')
  || E'\n\n-- ===== enum types =====\n' || coalesce((select txt from enums), '-- (none)')
  || E'\n\n-- ===== tables / constraints / RLS =====\n' || coalesce((select txt from tables), '')
  || E'\n\n-- ===== indexes (constraint-backed indexes excluded) =====\n' || coalesce((select txt from indexes), '')
  || E'\n\n-- ===== views =====\n' || coalesce((select txt from views), '-- (none)')
  || E'\n\n-- ===== functions (acl: who may EXECUTE; "=X" means PUBLIC) =====\n' || coalesce((select txt from funcs), '')
  || E'\n\n-- ===== triggers =====\n' || coalesce((select txt from trigs), '')
  || E'\n\n-- ===== row level security policies =====\n' || coalesce((select txt from pols), '')
  || E'\n';
$$;

revoke execute on function public.schema_snapshot() from public, anon, authenticated;
