-- User Relations Table Definition
-- ユーザー間の関係性（気になる、挨拶済みなど）を管理するテーブル

create table public.user_relations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- 自分 (ログインユーザー)
  target_car_id text not null, -- 相手の車ID (DOC_xxx)
  status text check (status in ('want', 'met')), -- ステータス (want:気になる, met:挨拶済)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- 同じ相手に対しては1つのレコードのみ（ユニーク制約）
  unique(user_id, target_car_id)
);

-- RLS (Row Level Security) Policies
alter table public.user_relations enable row level security;

-- 自分のデータだけ読み書き可能
create policy "Users can view their own relations"
  on public.user_relations for select
  using (auth.uid() = user_id);

create policy "Users can insert their own relations"
  on public.user_relations for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own relations"
  on public.user_relations for update
  using (auth.uid() = user_id);

create policy "Users can delete their own relations"
  on public.user_relations for delete
  using (auth.uid() = user_id);
