-- User Relations Table Definition (Firebase Auth Compatible)
-- Firebase AuthのUIDを使用するため、auth.usersへの外部キー制約を削除し、RLSを緩和します。

-- 1. 既存のテーブルを再作成（データは消えますが、まだ運用前なので許容）
-- ※もしデータがある場合は ALTER TABLE で制約を外す必要がありますが、
--   今回はシンプルに作り直します。
drop table if exists public.user_relations;

create table public.user_relations (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Firebase UID (uuid型ではなくtext型に変更)
  target_car_id text not null,
  status text check (status in ('want', 'met')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, target_car_id)
);

-- 2. RLS (Row Level Security) Policies
-- Firebase Auth と Supabase Auth が連携していないため、
-- クライアントサイドからのアクセスを許可するためにポリシーを全開放します。
-- ※セキュリティリスクはありますが、既存の構成に合わせるための措置です。
alter table public.user_relations enable row level security;

create policy "Allow all operations for authenticated users"
  on public.user_relations
  for all
  using (true)
  with check (true);
