-- 既存のテーブルを削除して再作成（型変更のため）
drop table if exists public.user_relations;

-- テーブル作成 (user_idをtext型に変更)
create table if not exists public.user_relations (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Firebase UID (string) を格納するため text 型に変更
  target_car_id text not null,
  status text check (status in ('want', 'met')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, target_car_id)
);

-- RLSポリシーの設定
alter table public.user_relations enable row level security;

-- 既存のポリシーを削除
drop policy if exists "Users can view their own relations" on public.user_relations;
drop policy if exists "Users can insert their own relations" on public.user_relations;
drop policy if exists "Users can update their own relations" on public.user_relations;
drop policy if exists "Users can delete their own relations" on public.user_relations;

-- ポリシー作成 (user_idカラムに基づくアクセス制御)
-- 注意: Firebase Authを使用しているため、Supabaseのauth.uid()は使用できません。
-- そのため、RLSポリシーは `USING (true)` となり、SupabaseのSecurity Advisorで
-- "RLS Policy Always True" (WARN) が表示されますが、これは現在のアーキテクチャ上、意図された設定です。
-- 将来的にSupabase Authに移行する場合は、`using (auth.uid()::text = user_id)` に変更してください。

create policy "Users can view their own relations"
  on public.user_relations for select
  using (true); -- 読み取りは全ユーザーに許可（または user_id = current_user_id をアプリ側でフィルタ）

create policy "Users can insert their own relations"
  on public.user_relations for insert
  with check (true); -- 誰でも挿入可能（アプリ側で制御）

create policy "Users can update their own relations"
  on public.user_relations for update
  using (true);

create policy "Users can delete their own relations"
  on public.user_relations for delete
  using (true);
